apiVersion: v1
kind: Service
metadata:
  name: demo1
spec:
  selector:
    app: demo1-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1-app
spec:
  selector:
    matchLabels:
      app: demo1-app
  replicas: 1
  template:
    metadata:
      labels:
        app: demo1-app
    spec:
      containers:
        - name: spring-test-app
          image: demo1
          # https://stackoverflow.com/a/42564211/1237627
          # Should reuse locally build image
          imagePullPolicy: Never
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"