FROM centos:latest
RUN yum install python3 -y
# pip3 install numpy
# pip3 install scikit-learn
# pip3 install pandas
COPY ./expensive_job.py /app
# Step-6 Writing and Running Python code
# vi mycode.py (Writing)
# python mycode.py (Running)