apiVersion: v1
kind: Namespace
metadata:
  name: my-test
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway
  namespace: my-test
spec:
  selector:
    istion: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - '*'


